# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

working_directory: ~/repo

jobs:
  build:
    docker:
      - image: circleci/node    
    steps:
      - checkout
      - run: sudo npm install gulp-cli -g
      - run: npm install 
      - run: composer i
      - run: gulp build 
