# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
workflows:
  build_and_test:
    jobs:
      - gulp

jobs:
  gulp:
    docker:
      - image: circleci/node
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: sudo npm install gulp-cli -g
      - run: npm install gulp -D
      - run: gulp build 
