# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
workflows:
  verify_standards:
    jobs:
      - standard:
          filters:
            branches:
              ignore:
                - gh-pages
      - autodoc:
          filters:
            branches:
              only:
                - dev 
          requires:
            - standard

working_directory: ~/repo

jobs:
  autodoc:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: git config --global user.name "guzmanjd86@gmail.com"
      - run: git config --global user.email "Danny Guzman"
      - run: composer i --no-dev
      - run: wget -O phpDoc.phar https://phpdoc.org/phpDocumentor.phar
      - run: chmod +x phpDoc.phar
      - run: ./phpDoc.phar . --force
      - run: git checkout gh-pages
      - run: rm -rf *
      - run: mv .docs/* .
      - run: rm -rf .docs/
      - run: git add .
      - run: git commit -m "Autogenerated docs via CircleCi"
      - run: git push origin gh-pages
      - run: git remote add codeworks https://github.com/CA-CODE-Works/CAWeb
      - run: git fetch codeworks
      - run: git pull codeworks gh-pages
      - run: git pull origin gh-pages
      - run: git add .
      - run: git commit -m "Autogenerated docs via CircleCi"
      - run: git push codeworks gh-pages 
      - run: git remote add cawebublishing https://github.com/CAWebPublishing/CAWeb
      - run: git fetch cawebublishing
      - run: git pull cawebublishing gh-pages
      - run: git pull origin gh-pages
      - run: git add .
      - run: git commit -m "Autogenerated docs via CircleCi"
      - run: git push cawebublishing gh-pages

  standard:
      docker:
        - image: circleci/php:7.4
      steps:
        - checkout
        - run: composer i --no-dev
        - run: 
            command: |
              declare -a files=( 
                'inc/admin-bar.php'
                'inc/admin-post.php'
                'inc/branding.php'
                'inc/class-caweb-customize-icon-control.php'
                'inc/class-caweb-nav-menu.php'
                'inc/class-caweb-nav-menu-walker.php'
                'inc/customizer.php'
                'inc/filters.php'
                'inc/functions.php'
                'inc/icon-library.php'
                'inc/live-drafts.php'
                'inc/options.php'
                'inc/shortcodes.php'
                'inc/tinymce.php'
                'inc/widgets.php'
                '404.php' 
                'archive.php' 
                'author.php' 
                'category.php' 
                'date.php' 
                'footer.php' 
                'functions.php' 
                'header.php'
                'index.php'
                'page.php'
                'single.php'
                'tag.php'
                )
              for f in ${files[@]}; do
                  if [ -n "$( ./vendor/bin/phpcs $f )" ]; then
                    echo "$( ./vendor/bin/phpcs $f )"
                    exit 1
                  fi
              done


              