# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
workflows:
  verify_standards:
    jobs:
      - standard

working_directory: ~/repo

jobs:
  standard:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: composer i --no-dev
      - run: ls -al
      - run: 
          command: |
            clean=$(./vendor/bin/phpcs ./functions.php)
            if [ -z "$clean" ]; then
              print 'functions.php failed WordPress Coding Standards'
              exit 1
            fi